from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.responses import FileResponse
import os
import shutil
import tempfile
import subprocess
import time
import json

from one import run_pipeline

app = FastAPI(title="Manim Pipeline Controller")


@app.post("/generate-code")
async def generate_code(
    pdf: UploadFile = File(...),
    query: str = Form(...)
):
    
    if not pdf.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files allowed.")


    workdir = tempfile.mkdtemp(prefix="manim_pipeline_")
    pdf_path = os.path.join(workdir, pdf.filename)


    with open(pdf_path, "wb") as f:
        shutil.copyfileobj(pdf.file, f)


    script_path = os.path.join(workdir, "gemini_output.txt")
    manim_path = os.path.join(workdir, "auto_generated_manim.py")


    run_pipeline(
        pdf_path=pdf_path,
        query=query,
        db_path=os.path.join(workdir, "chroma_db"),
        output_script_file=script_path,
        output_manim_file=manim_path
    )


    if not os.path.exists(manim_path):
        raise HTTPException(status_code=500, detail="Failed to generate Manim file.")


    return FileResponse(
        manim_path,
        filename="auto_generated_manim.py",
        media_type="text/x-python"
    )



GENERATED_DIR = "generated"
COUNTER_FILE = "counter.json"

# make sure generated folder exists
os.makedirs(GENERATED_DIR, exist_ok=True)


def next_id():
    """
    Returns the next incremental ID for file names.
    Stores count in counter.json.
    """
    if not os.path.exists(COUNTER_FILE):
        with open(COUNTER_FILE, "w") as f:
            json.dump({"count": 1}, f)
        return 1

    with open(COUNTER_FILE, "r") as f:
        data = json.load(f)

    data["count"] += 1

    with open(COUNTER_FILE, "w") as f:
        json.dump(data, f)

    return data["count"]


@app.post("/generate-video")
async def generate_video(file: UploadFile = File(...), query: str = "Explain"):
    """
    1. Save uploaded PDF
    2. Generate unique counter-based ID
    3. Run pipeline to create Manim code
    4. Render the video
    5. Return the MP4 file
    """
    # Step 1 — save uploaded PDF
    pdf_path = os.path.join(GENERATED_DIR, file.filename)
    with open(pdf_path, "wb") as f:
        f.write(await file.read())

    # Step 2 — get next incremental ID
    file_id = next_id()

    # Folder structure: generated/<id>/
    output_dir = os.path.join(GENERATED_DIR, str(file_id))
    os.makedirs(output_dir, exist_ok=True)

    # Output file names
    script_file = os.path.join(output_dir, f"gemini_output_{file_id}.txt")
    manim_file = os.path.join(output_dir, f"auto_generated_manim_{file_id}.py")

    # Step 3 — Run AI pipeline
    run_pipeline(
        pdf_path=pdf_path,
        query=query,
        output_script_file=script_file,
        output_manim_file=manim_file,
        db_path="./chroma_db",
        gemini_model="gemini-2.0-flash",
        n_retrieved=3
    )

    # Step 4 — Render video using Manim
    command = [
        "manim",
        "-qh",
        manim_file,
        "AutoGeneratedVideo",
        "--media_dir", output_dir
    ]
    subprocess.run(command, check=False)

    # Step 5 — Find the generated MP4
    video_dir = os.path.join(output_dir, "videos", f"auto_generated_manim_{file_id}", "1080p30")
    video_file = None

    for f in os.listdir(video_dir):
        if f.endswith(".mp4"):
            video_file = os.path.join(video_dir, f)
            break

    if video_file is None:
        return {"error": "Video not generated. Check pipeline or Manim logs."}

    # Return as downloadable response
    return FileResponse(
        video_file,
        media_type="video/mp4",
        filename=f"output_{file_id}.mp4"
    )