# Generated by pipeline_to_manim_720p.py — Manim v0.19.0
from manim import *
from manim import config
config.pixel_width = 1920
config.pixel_height = 1080
config.frame_rate = 30

class AutoGeneratedVideo(Scene):
    def construct(self):
        self.scene_introduction()
        self.scene_defining_slope()
        self.scene_calculating_slope()
        self.scene_types_of_slopes()
        self.scene_slope_in_real_life()
        self.scene_conclusion()

    def scene_introduction(self):
        title = Text("Understanding Slope")
        title.to_edge(UP)
        self.play(Write(title))

        rectangle = SurroundingRectangle(title, color=WHITE, buff=0.2)
        self.play(Create(rectangle))

        arrow = Arrow(start=DOWN + LEFT * 5, end=UP + RIGHT * 5)
        self.play(Create(arrow))

        self.wait(1)
        self.play(FadeOut(title, rectangle, arrow))

    def scene_defining_slope(self):
        axes = Axes()
        axes.shift(DOWN * 2)
        self.play(Create(axes))

        rise_text = Text("Rise", color=GREEN).move_to([1, 1, 0])
        run_text = Text("Run", color=RED).move_to([2, -1, 0])
        self.play(Write(rise_text), Write(run_text))

        line = Line([-1, -1, 0], [2, 1, 0])
        self.play(Create(line))

        rise_arrow = Arrow(start=[2, 1, 0], end=[2, 2, 0], color=GREEN)
        rise_label = Text("Rise", color=GREEN).next_to(rise_arrow, RIGHT)
        self.play(Create(rise_arrow), Write(rise_label))

        run_arrow = Arrow(start=[2, 1, 0], end=[3, 1, 0], color=RED)
        run_label = Text("Run", color=RED).next_to(run_arrow, UP)
        self.play(Create(run_arrow), Write(run_label))

        self.wait(1)
        self.play(FadeOut(axes, rise_text, run_text, line, rise_arrow, rise_label, run_arrow, run_label))

    def scene_calculating_slope(self):
        axes = Axes()
        axes.shift(DOWN * 2)
        self.play(Create(axes))

        dot1 = Dot(axes.coords_to_point(-1, -1), color=BLUE)
        dot1_label = Text("(x1, y1)", color=BLUE).next_to(dot1, DOWN + LEFT)
        self.play(Create(dot1), Write(dot1_label))

        dot2 = Dot(axes.coords_to_point(2, 1), color=YELLOW)
        dot2_label = Text("(x2, y2)", color=YELLOW).next_to(dot2, UP + RIGHT)
        self.play(Create(dot2), Write(dot2_label))

        line = Line(axes.coords_to_point(-1, -1), axes.coords_to_point(2, 1))
        self.play(Create(line))

        slope_eq = Text("Slope (m) = (y2 - y1) / (x2 - x1)")
        slope_eq.to_edge(UP)
        self.play(Write(slope_eq))

        self.wait(1)
        self.play(FadeOut(axes, dot1, dot1_label, dot2, dot2_label, line, slope_eq))

    def scene_types_of_slopes(self):
        axes = Axes(x_range=[-5, 5, 1], y_range=[-5, 5, 1])
        axes.shift(DOWN * 2)
        self.play(Create(axes))

        positive_line = Line(axes.coords_to_point(-3, -3), axes.coords_to_point(3, 3), color=GREEN)
        positive_label = Text("Positive Slope", color=GREEN).next_to(positive_line, RIGHT)
        self.play(Create(positive_line), Write(positive_label))

        negative_line = Line(axes.coords_to_point(-3, 3), axes.coords_to_point(3, -3), color=RED)
        negative_label = Text("Negative Slope", color=RED).next_to(negative_line, RIGHT)
        self.play(Create(negative_line), Write(negative_label))

        zero_line = Line(axes.coords_to_point(-3, 0), axes.coords_to_point(3, 0), color=BLUE)
        zero_label = Text("Zero Slope", color=BLUE).next_to(zero_line, RIGHT)
        self.play(Create(zero_line), Write(zero_label))

        undefined_line = Line(axes.coords_to_point(0, -3), axes.coords_to_point(0, 3), color=ORANGE)
        undefined_label = Text("Undefined Slope", color=ORANGE).next_to(undefined_line, UP)
        self.play(Create(undefined_line), Write(undefined_label))

        self.wait(1)
        self.play(FadeOut(axes, positive_line, positive_label, negative_line, negative_label, zero_line, zero_label, undefined_line, undefined_label))

    def scene_slope_in_real_life(self):
        title = Text("Real-World Applications of Slope")
        self.play(Write(title))

        # Placeholder for images
        road_text = Text("Road (Uphill)").move_to(UP*2)
        roof_text = Text("House Roof").move_to(DOWN*2)
        self.play(Write(road_text), Write(roof_text))

        self.wait(1)
        self.play(FadeOut(title, road_text, roof_text))

    def scene_conclusion(self):
        slope_text = Text("Slope: Rise Over Run")
        self.play(Write(slope_text))

        thank_you_text = Text("Thank You!")
        thank_you_text.next_to(slope_text, DOWN, buff=1)
        self.play(Write(thank_you_text))

        self.wait(2)
        self.play(FadeOut(slope_text, thank_you_text))
